const $ = (id) => document.getElementById(id);
let latest;
let userWeightOverride=false;

function money(value) { return Number(value).toFixed(1); }
function setText(id, value) { const element=$(id); if(element) element.textContent=value; }

function drawScatter(data) {
  const svg = $("scatter"), w = 700, h = 330, pad = {l:52,r:25,t:22,b:42};
  svg.setAttribute("viewBox", `0 0 ${w} ${h}`);
  const points = data.historical.map(d => ({x:d.eps,y:d.pe,label:d.year}));
  points.push({x:data.assumptions.forecast_eps,y:data.fair_pe,label:"模型",forecast:true});
  const xs=points.map(p=>p.x), ys=points.map(p=>p.y), xmin=Math.min(...xs)-1, xmax=Math.max(...xs)+1, ymin=Math.min(...ys)-1, ymax=Math.max(...ys)+1;
  const sx=x=>pad.l+(x-xmin)/(xmax-xmin)*(w-pad.l-pad.r), sy=y=>h-pad.b-(y-ymin)/(ymax-ymin)*(h-pad.t-pad.b);
  let html="";
  for(let i=0;i<5;i++){const y=pad.t+i*(h-pad.t-pad.b)/4; const val=ymax-i*(ymax-ymin)/4; html+=`<line x1="${pad.l}" y1="${y}" x2="${w-pad.r}" y2="${y}" stroke="#dde1da"/><text x="${pad.l-10}" y="${y+4}" text-anchor="end" fill="#78817d" font-size="11">${val.toFixed(1)}x</text>`}
  html+=`<text x="${w/2}" y="${h-5}" text-anchor="middle" fill="#78817d" font-size="11">每股盈餘 EPS</text>`;
  points.forEach(p=>{const color=p.forecast?"#a94f36":"#1f5c48",r=p.forecast?8:5;html+=`<circle cx="${sx(p.x)}" cy="${sy(p.y)}" r="${r}" fill="${color}" opacity="${p.forecast?1:.82}"/><text x="${sx(p.x)}" y="${sy(p.y)-10}" text-anchor="middle" fill="${color}" font-size="10" font-weight="700">${p.label}</text>`});
  svg.innerHTML=html;
}

function render(data) {
  latest=data;
  const a=data.assumptions;
  setText("company",data.company_name);setText("stockCode",data.ticker);setText("currentPrice",money(data.current_price));setText("asOf",data.source_notes[0].as_of);
  setText("bearValue",money(data.bear_value));setText("fairValue",money(data.fair_value));setText("bullValue",money(data.bull_value));
  setText("upside",`${data.upside_pct>=0?"+":""}${data.upside_pct.toFixed(1)}%`);setText("classification",data.classification);setText("confidence",data.confidence);
  for(const name of ["bear","base","bull"]){
    const s=a.scenarios[name];
    setText(`${name}Inputs`,`P/E ${money(s.pe_value)}｜P/B ${money(s.pb_value)}`);
    setText(`${name}Weight`,`權重 P/E ${(a.model_weights.pe*100).toFixed(1)}% · P/B ${(a.model_weights.pb*100).toFixed(1)}%`);
  }
  const rr=a.rerating;const signed=v=>`${v>=0?"+":""}${v.toFixed(1)}%`;setText("peTarget",money(data.pe_target_price));setText("historicalFairPe",`${a.historical_fair_pe.toFixed(2)}x`);setText("currentRegimePe",rr.current_regime_pe==null?"資料不足":`${rr.current_regime_pe.toFixed(2)}x`);setText("fairPe",`${data.fair_pe.toFixed(2)}x`);setText("impliedPe",`${data.implied_forward_pe.toFixed(2)}x`);setText("historicalPremium",signed(a.premium_to_historical_pe_pct));setText("pePremium",signed(a.premium_to_fair_pe_pct));setText("historyPeStats",`${a.historical_median_pe.toFixed(2)}x／${a.historical_mean_pe.toFixed(2)}x`);setText("recentPe",`${a.recent_pe.toFixed(2)}x（3年）`);setText("regressionStats",`${a.regression_pe.toFixed(2)}x／${a.regression_r2.toFixed(3)}`);setText("rerating",`${rr.label} ${signed((rr.rerating_ratio-1)*100)}`);setText("regimeSource",rr.source?`${rr.source}（${rr.observation_count}筆）`:"資料不足");setText("regimeStats",rr.current_regime_pe==null?"—":`${rr.current_regime_pe.toFixed(2)}x／${rr.current_regime_mad.toFixed(2)}x`);setText("persistence",`${rr.persistence_count}／${rr.observation_count}（${(rr.persistence_score*100).toFixed(0)}%）`);setText("fundamentalConfirm",`${(rr.fundamental_score*100).toFixed(0)}%${rr.accounting_regime_change?" · 會計制度變更":""}`);setText("layerWeights",`歷史 ${(rr.historical_layer_weight*100).toFixed(0)}% · Regime ${(rr.effective_regime_weight*100).toFixed(0)}%`);setText("basePeAdjust",`${a.base_pe_before_rerating.toFixed(2)}x／${a.base_pe_after_rerating.toFixed(2)}x`);setText("spreadStats",`${a.pe_mad.toFixed(2)}x／${a.pe_spread.toFixed(2)}x`);setText("effectiveWeights",`迴歸 ${(a.pe_reference_weights[0]*100).toFixed(0)}% · 近期 ${(a.pe_reference_weights[1]*100).toFixed(0)}% · 長期 ${(a.pe_reference_weights[2]*100).toFixed(0)}%`);setText("confidenceScore",`${a.confidence_score.toFixed(3)}（${data.confidence}）`);
  const pb=a.pb_model.traditional,apb=a.pb_model.adjusted;setText("pbTarget",money(data.pb_target_price));setText("historicalFairPb",`${pb.historical_fair_pb.toFixed(2)}x`);setText("currentRegimePb",pb.current_regime_pb==null?"資料不足":`${pb.current_regime_pb.toFixed(2)}x`);setText("fairPb",`${data.fair_pb.toFixed(2)}x`);setText("pbScenarios",`${pb.bear_pb.toFixed(2)}／${pb.base_pb.toFixed(2)}／${pb.bull_pb.toFixed(2)}x`);setText("pbMedians",`${pb.historical_median.toFixed(2)}／${pb.recent_median.toFixed(2)}x`);setText("pbRegime",`${pb.regime_ratio.toFixed(2)}x／${(pb.persistence_score*100).toFixed(0)}%`);setText("pbScores",`${(pb.fundamental_score*100).toFixed(0)}%／${(pb.book_value_quality_score*100).toFixed(0)}%／${(pb.accounting_comparability_score*100).toFixed(0)}%`);setText("pbLayerWeights",`歷史 ${(pb.historical_weight*100).toFixed(0)}% · Regime ${(pb.regime_weight*100).toFixed(0)}%`);setText("pbSpread",`${pb.pb_mad.toFixed(2)}／${pb.spread.toFixed(2)}x`);setText("forecastBps",a.forecast_bps.toFixed(1));setText("currentPb",`${pb.current_pb.toFixed(2)}x`);setText("adjustedBps",apb.bps.toFixed(1));setText("adjustedCurrentPb",`${apb.current_pb.toFixed(2)}x`);setText("contextTraditionalPb",`${pb.current_pb.toFixed(2)}x`);setText("adjustedPbStatus",apb.status_label);setText("adjustedPbDifference",signed(apb.discount_vs_traditional_pct));setText("adjustedFairPb",apb.fair_pb==null?"資料不足":`${apb.fair_pb.toFixed(2)}x`);setText("adjustedIncluded",apb.included_in_composite?"是":"否");setText("adjustedInterpretation",`以調整後淨值衡量，目前市場 P/B 為 ${apb.current_pb.toFixed(2)}x，較傳統口徑 ${pb.current_pb.toFixed(2)}x 低 ${Math.abs(apb.discount_vs_traditional_pct).toFixed(1)}%。這代表市場看起來沒有傳統 P/B 顯示得昂貴，但目前無法判斷 ${apb.current_pb.toFixed(2)}x 本身是便宜、合理或昂貴。`);setText("adjustedWarning",apb.warning);setText("pbPremiums",`${pb.premium_to_historical_pct>=0?"+":""}${pb.premium_to_historical_pct.toFixed(1)}%／${pb.premium_to_final_pct>=0?"+":""}${pb.premium_to_final_pct.toFixed(1)}%`);setText("requiredBps",`${pb.required_bps.toFixed(1)} 元`);setText("pbConfidence",`${pb.confidence_score.toFixed(3)}（${pb.confidence}）`);setText("version",data.model_version);
  if(apb.status==="provisional"){
    const p=apb.provisional,b=apb.anchors.traditional_bridge,r=apb.anchors.roe_based,w=apb.anchor_weights;
    setText("adjustedFairPb",`${p.base_pb.toFixed(2)}x`);setText("adjustedPbRange",`${p.bear_pb.toFixed(2)}x ～ ${p.bull_pb.toFixed(2)}x`);setText("adjustedFairValue",`NT$ ${money(p.base_value)}`);setText("adjustedValueRange",`NT$ ${money(p.bear_value)} ～ ${money(p.bull_value)}`);setText("adjustedConfidence",`${p.confidence.toFixed(3)}（${apb.confidence}）`);setText("bridgePb",`${b.pb.toFixed(3)}x（信心 ${b.confidence.toFixed(3)}）`);setText("comparabilityBridge",`${(b.accounting_comparability_score*100).toFixed(0)}%／${b.comparability_factor.toFixed(2)}`);setText("roeBasedPb",r?`${r.pb.toFixed(3)}x（信心 ${r.confidence.toFixed(2)}）`:"不可用");setText("roeInputs",r?`${(r.normalized_roe*100).toFixed(1)}%／${(r.growth_rate*100).toFixed(1)}%／${(r.required_return*100).toFixed(1)}%${r.required_return_is_assumption?"（r 為假設）":""}`:"—");setText("peerAnchor",apb.anchors.peer?`${apb.anchors.peer.pb.toFixed(2)}x`:"無資料，不製造估值");setText("anchorWeights",`Bridge ${(w.traditional_bridge*100).toFixed(0)}% · ROE ${((w.roe_based||0)*100).toFixed(0)}% · Peer ${((w.peer||0)*100).toFixed(0)}%`);setText("adjustedHistoryCount",`${apb.historical_observation_count} 筆；因此使用 provisional`);setText("adjustedInterpretation",`Adjusted P/B 暫估合理倍數為 ${p.base_pb.toFixed(2)}x，並以較寬的 ${p.bear_pb.toFixed(2)}x～${p.bull_pb.toFixed(2)}x 表達資料不足的不確定性。目前市場 ${apb.current_pb.toFixed(2)}x 只作 sanity check，沒有進入加權合理倍數。`);
  }
  const ec=data.composite,ew=ec.expanded_weights;setText("compositeValue",money(data.fair_value));setText("expandedCompositeValue",money(ec.expanded_fair_value));setText("expandedPbFamily",`NT$ ${money(ec.expanded_pb_family_value)}`);setText("expandedPeWeight",`${(ew.pe*100).toFixed(1)}%`);setText("expandedTraditionalWeight",`${(ew.traditional_pb*100).toFixed(1)}%`);setText("expandedAdjustedWeight",`${(ew.adjusted_pb*100).toFixed(1)}%（上限 15%）`);setText("peFairValue",`NT$ ${money(data.pe_target_price)}`);setText("pbFairValue",`NT$ ${money(data.pb_target_price)}`);
  setText("modelWeights",`P/E ${(a.model_weights.pe*100).toFixed(1)}% · P/B ${(a.model_weights.pb*100).toFixed(1)}%`);setText("safetyMargin",`${a.safety_margin_pct.toFixed(1)}%`);if(!userWeightOverride){$("peWeight").value=(a.model_weights.pe*100).toFixed(1);setText("weightOut",`P/E ${(a.model_weights.pe*100).toFixed(1)}% · P/B ${(a.model_weights.pb*100).toFixed(1)}%`);}
  setText("requiredEps",`${a.required_eps.toFixed(2)} 元 EPS`);setText("reversePrice",`NT$ ${money(data.current_price)}`);setText("reverseCurrentEps",`${a.forecast_eps.toFixed(2)} 元`);setText("reverseImpliedPe",`${data.implied_forward_pe.toFixed(2)}x`);setText("reversePe",`${data.fair_pe.toFixed(2)}x`);setText("reverseEps",`${a.required_eps.toFixed(2)} 元`);
  const heat=data.valuation_heat, pct=v=>v==null?"資料不足":`${v>=0?"+":""}${(v*100).toFixed(1)}%`, pe=v=>v==null?"資料不足":`${v.toFixed(2)}x`;
  setText("heatScore",`${heat.heat_score} / 100`);setText("heatLabel",heat.heat_label);setText("heatConclusion",heat.conclusion);setText("heatForwardPe",pe(heat.forward_pe.fy1));setText("heatFairPe",pe(heat.final_fair_pe));setText("heatFairPremium",pct(heat.premium_to_final_fair));setText("heatHistoricalPe",pe(heat.historical_fair_pe));setText("heatHistoricalPremium",pct(heat.premium_to_historical));setText("heatEpsComparison",`${heat.required_eps.toFixed(2)}／${heat.base_forecast_eps.toFixed(2)} 元`);setText("heatEpsGap",pct(heat.required_eps_gap));setText("heatHorizon",heat.priced_in_horizon);setText("heatTrailingPe",pe(heat.trailing_pe));setText("heatRegimePe",pe(heat.current_regime_pe));setText("heatForwardCurve",["fy1","fy2","fy3"].map(k=>`${k.toUpperCase()} ${pe(heat.forward_pe[k])}`).join("／"));setText("heatCatchup",heat.earnings_catch_up_score==null?"資料不足":heat.earnings_catch_up_score.toFixed(2));setText("heatCompression",pct(heat.pe_compression_2y));setText("heatAttribution",heat.price_attribution?`P/E 擴張占 ${(heat.price_attribution.multiple_expansion_share*100).toFixed(0)}%`:"資料不足");setText("heatAnalystPe",pe(heat.analyst_target_implied_pe));setText("heatLimitations",heat.data_limitations.length?heat.data_limitations.join("、"):"無");
  const labels={bear:"悲觀",base:"中性",bull:"樂觀"};const pes=a.scenarios;
  $("matrixHead").innerHTML=`<tr><th>EPS 情境</th><th>悲觀 P/E<br>${pes.bear.pe.toFixed(2)}x</th><th>中性 P/E<br>${pes.base.pe.toFixed(2)}x</th><th>樂觀 P/E<br>${pes.bull.pe.toFixed(2)}x</th></tr>`;
  $("matrixBody").innerHTML=a.valuation_matrix.map(row=>`<tr><th>${labels[row.scenario]} EPS<br>${row.eps.toFixed(2)}</th><td>${money(row.prices.bear)}</td><td class="${row.scenario==='base'?'focus':''}">${money(row.prices.base)}</td><td>${money(row.prices.bull)}</td></tr>`).join("");
  const pbs=a.pb_model.pb_scenarios;$("pbMatrixHead").innerHTML=`<tr><th>BPS 情境</th><th>悲觀 P/B<br>${pbs.bear.toFixed(2)}x</th><th>中性 P/B<br>${pbs.base.toFixed(2)}x</th><th>樂觀 P/B<br>${pbs.bull.toFixed(2)}x</th></tr>`;$("pbMatrixBody").innerHTML=pb.valuation_matrix.map(row=>`<tr><th>${labels[row.scenario]} BPS<br>${row.bps.toFixed(2)}</th><td>${money(row.prices.bear)}</td><td class="${row.scenario==='base'?'focus':''}">${money(row.prices.base)}</td><td>${money(row.prices.bull)}</td></tr>`).join("");
  setText("sourceNote",data.source_notes.map(source=>`${source.name}（截至 ${source.as_of}）：${source.note}`).join("；")+"。");
  setText("epsMethod",a.forecast_method);
  setText("bpsMethod",a.bps_method);
  const direction=a.eps_pe_correlation<0?"負相關":"正相關";setText("correlationNote",`相關係數 ${a.eps_pe_correlation.toFixed(3)}（${direction}），R² ${a.regression_r2.toFixed(3)}。R² 會自動調整迴歸權重；未使用權重按 70%／30% 回補近期與長期中位數。`);
  $("historyRows").innerHTML=data.historical.map(d=>`<tr><td>${d.year}</td><td>${d.eps.toFixed(2)}</td><td>${d.pe.toFixed(1)}x</td><td>${d.bps.toFixed(1)}</td><td>${d.pb.toFixed(2)}x</td></tr>`).join("");
  drawScatter(data);
}

async function calculate() {
  const peWeight=Number($("peWeight").value)/100;
  const eps=Number($("eps").value);const payload={ticker:$("ticker").value.trim(),forecast_eps:eps,forecast_bps:Number($("bps").value)};if(userWeightOverride){payload.pe_weight=peWeight;payload.pb_weight=1-peWeight;payload.weights_are_final=true;}
  try{const res=await fetch("/api/valuation",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!res.ok)throw new Error((await res.json()).detail||"估值服務暫時無法使用");render(await res.json());$("searchHint").textContent="MVP 第一階段支援 2881 富邦金";$("searchHint").className=""}catch(err){$("searchHint").textContent=err.message;$("searchHint").className="error"}
}

function syncControls(){setText("epsOut",Number($("eps").value).toFixed(2));setText("bpsOut",Number($("bps").value).toFixed(1));const w=Number($("peWeight").value);setText("weightOut",`P/E ${w.toFixed(1)}% · P/B ${(100-w).toFixed(1)}%`);calculate()}
let timer;["eps","bps"].forEach(id=>$(id).addEventListener("input",()=>{clearTimeout(timer);timer=setTimeout(syncControls,80)}));$("peWeight").addEventListener("input",()=>{userWeightOverride=true;clearTimeout(timer);timer=setTimeout(syncControls,80)});
$("searchForm").addEventListener("submit",e=>{e.preventDefault();calculate()});
$("reset").addEventListener("click",()=>{userWeightOverride=false;$("eps").value=10.95;$("bps").value=83.7;calculate()});
$("toggleTable").addEventListener("click",()=>{const wrap=$("tableWrap");wrap.hidden=!wrap.hidden;$("toggleTable").textContent=wrap.hidden?"展開資料":"收合資料"});
calculate();
